### PR TITLE
Change Ruby version instruction to 2.6.4

### PR DESCRIPTION
**Pull request by mluisbrown**

### CODE REVIEW

**Review by DeFrenZ — APPROVED** [review]
I had to do that afterwards anyway, so makes sense to make it direct 👌

**Comment by mluisbrown** [comment]
Unsure how often this changes. Maybe we should make the instruction version agnostic, and put something like "Find what is the required Ruby version from the `.ruby-version` file in the root of the project" 🤔

**Review by danspndl — APPROVED** [review]
🚢

**Comment by Ben-Henshall** [comment]
@mluisbrown Has this requirement changed recently? Might be worth announcing in #ios-pedia to ensure everyone is on the correct version, so this sort of thing isn't always immediately recognisable as a version issue

**Review by Ben-Henshall — APPROVED** [review]

**Comment by sdaniel55** [comment]
> @Ben-Henshall: Has this requirement changed recently? Might be worth announcing in #ios-pedia to ensure everyone is on the correct version, so this sort of thing isn't always immediately recognisable as a version issue

It was changed with the Xcode 11 migration

**Pull request merged**
