### PR TITLE
Add TabBarAndNavigationFramework.md (WIP)

### PR DESCRIPTION
**Pull request by inamiy**
TBD

### CODE REVIEW

**Comment by zzcgumn** [comment]
> in contrast to Cocoa's Responder Chain system.

My experience from working with one single, centralised router is that this entity can become very complicated. I came across this approach while working with a cross platform framework called MvvmCross. 

Therefore I think we should try to architecture the routing service with a domain model in mind and think more like the responder chain and less like notification the centre.

**Comment by inamiy** [comment]
@zzcgumn 
Router can be split into multiple nested structure, but the event needs to be handled and routed from top to bottom, just like Universal Link's URL path structure. 
So, these nested structures will be hidden from outside, and for any presenting screens, the core Router is only visible as an entrypoint facade.

**Comment by RuiAAPeres** [comment]
Closing this for now. Please re-open when you can continue. ❤️

**Comment by inamiy** [comment]
This proposal has been superceded by https://github.com/Babylonpartners/ios-playbook/pull/232 Root & Tab Framework.

**Pull request closed without merging**
