### PR TITLE
Update SnowplowHowTo.md

### PR DESCRIPTION
**Pull request by ilyapuchka**

### CODE REVIEW

**Comment by ilyapuchka** [comment]
@inamiy can you please check if there are other changes needed to this guide after your recent changes to analytics? 🙏

**Comment by diegopetrucci** [comment]
Yes I think the recommendations on how to test it should be updated

**Review by diegopetrucci — APPROVED** [review]

**Review by inamiy — APPROVED** [review]
There requires more editing as I changed in https://github.com/Babylonpartners/babylon-ios/pull/7397 , but I will take care of the rest later 👍

**Comment by ilyapuchka** [comment]
@inamiy you can just edit it in this PR, no pressure, I was just looking into it and remembered that there were some changes recently.

**Comment by inamiy** [comment]
@ilyapuchka Ready to go. Please check :)

**Review by diegopetrucci — APPROVED** [review]
🚀

**Review by zzcgumn — APPROVED** [review]
Thanks for updating this.

**Pull request merged**
