### PR TITLE
Update release documentation

### PR DESCRIPTION
**Pull request by danspndl**
## Why?

A step shouldn't be in this doc 👀 

## How?

Removed sensitive section from release doc

With ❤️

### CODE REVIEW

**Review by viorel15 — APPROVED** [review]
👍

**Comment by j531** [comment]
Will this be documented elsewhere?

**Comment by NSMyself** [comment]
Why is this sensitive btw?

**Comment by sdaniel55** [comment]
@j531 It's added to the confluence page

**Comment by sdaniel55** [comment]
> Why is this sensitive btw?

@NSMyself https://babylonhealth.slack.com/archives/C011DNRDXRQ/p1586873959072600?thread_ts=1586859180.062400&cid=C011DNRDXRQ

**Review by NSMyself — APPROVED** [review]

**Pull request merged**
