### PR TITLE
👋

### PR DESCRIPTION
**Pull request by NSMyself**
Like this @sdaniel55 ?

### CODE REVIEW

**Review by zopa-simon-cass — APPROVED** [review]
:elmo-rise:

**Comment by NSMyself** [comment]
Oh i need to run ruby as well.

image

**Comment by sdaniel55** [comment]
tried running the script locally, I think we can't have squads without members
```
➜  ios-playbook git:(NSMyself-patch-3) ✗ ruby scripts/squads.rb
Traceback (most recent call last):
	4: from scripts/squads.rb:56:in `<main>'
	3: from scripts/squads.rb:25:in `html_table'
	2: from scripts/squads.rb:25:in `map'
	1: from scripts/squads.rb:26:in `block in html_table'
scripts/squads.rb:13:in `row_with_members': undefined method `count' for nil:NilClass (NoMethodError)
```

**Review by danspndl — APPROVED** [review]
😭

**Comment by NSMyself** [comment]
Yup, I had to delete the entire squad. Working now

**Pull request merged**
