### PR TITLE
move checkboxes to the PR template

### PR DESCRIPTION
**Pull request by ilyapuchka**
It occurred to me that these checkboxes may be better in PR template rather than proposal document itself.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
They can be in both, no?

**Comment by ilyapuchka** [comment]
"what's the point?" 😄

**Comment by ilyapuchka** [comment]
I mean one place is enough, if in doc is fine, then fine, just thought that PR template is a better place and in doc it is a bit redundant

**Comment by RuiAAPeres** [comment]
Not all PR's against this repo will be a proposal.

**Comment by ilyapuchka** [comment]
Sure, but we can have multiple templates, you'll be able to select type of PR when creating it. Quite handy.

**Comment by ilyapuchka** [comment]
Some more details here https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/

**Comment by RuiAAPeres** [comment]
If the goal is to use PR's templates, then delete the proposal template altogether. Thanks.

**Comment by ilyapuchka** [comment]
@RuiAAPeres I don't think we should do that because PR template is just for description of the PR, but what we submit in the PR is the document that needs the template.

**Comment by RuiAAPeres** [comment]
@ilyapuchka you are absolutely right. 👍

**Pull request merged**
