### PR TITLE
Added myself to the team and fixed a broken link to the slack guide

### PR DESCRIPTION
**Pull request by nikolay-bab**

### CODE REVIEW

**Review by j531 — APPROVED** [review]
LGTM. FYI you've got changes to the Danger Rules doc in here as well. If that's intentional, cc @AliSoftware

**Review by konrad-em — APPROVED** [review]
Does it mean we can't use `#IgnoreSDKChanges` anymore?

**Comment by nikolay-bab** [comment]
Sorry about that, it's not intentional – I don't have a clue how it happened. 😮

**Review by danspndl — APPROVED** [review]
🎉

**Comment by nikolay-bab** [comment]
I reverted the DangerRules.md changes :))

**Comment by j531** [comment]
> I reverted the DangerRules.md changes :))

No problem, nice! 👍

**Pull request merged**
