### PR TITLE
Good Bye Rui… 😢

### PR DESCRIPTION
**Pull request by AliSoftware**
I know it's still a fresh wound, but while I'm doing multiple other PRs on the playbook, I figured we should update this too while I'm at it… 😔

Rui Meme

### CODE REVIEW

**Comment by AliSoftware** [comment]
btw @AnnKatF @dmcrodrigues should you still be labeled "Chapter Leads" or should we list you under "Engineering Managers" now? 🤔

**Review by inamiy — APPROVED** [review]
We are always watching you! (Credit: @Ben-Henshall )

**Review by mluisbrown — APPROVED** [review]
😭

**Comment by AliSoftware** [comment]
@ilyapuchka I was waiting for @dmcrodrigues and @AnnKatF to answer my question above before merging this... 🤷‍♂

**Comment by AnnKatF** [comment]
You can leave us as Chapter Leads - that’s the official title 🙃

**Pull request merged**
