### PR TITLE
Signing off 👋

### PR DESCRIPTION
**Pull request by andersio**

### CODE REVIEW

**Review by danspndl — CHANGES_REQUESTED** [review]
you didn't run the script to update the table 😬

**Review by daniloaliberti — APPROVED** [review]
😢 😭 😞 :try_not_to_cry:

**Comment by andersio** [comment]
@sdaniel55 argh I thought there is a CI job to regenerate that. 2020 goal idea for you? 😄

**Comment by sdaniel55** [comment]
> @andersio argh I thought there is a CI job to regenerate that. 2020 goal idea for you? 😄

we don't have CI here 🙈 I guess it would be possible with a quick GH Action though...

**Comment by viorel15** [comment]
Ok. Thank you. Bye.

**Review by danspndl — APPROVED** [review]
👋 😢

**Comment by NSMyself** [comment]
It's been a pleasure Anders, best of luck 👋

**Review by NSMyself — APPROVED** [review]

**Review by Ben-Henshall — APPROVED** [review]
elmo

**Comment by RuiAAPeres** [comment]
Wish you the best for whatever comes next. 👍

**Review by karabatov — APPROVED** [review]
byeee

Good luck with whatever comes next!

**Review by RuiAAPeres — APPROVED** [review]

**Review by mluisbrown — APPROVED** [review]

**Comment by sergdort** [comment]
image

**Pull request merged**
